### ISSUE TITLE
Develop Pseudo Code

### ISSUE THREAD

**Issue by rautranjan** [rautranjan/os-ssd-scheduler#3]
Develop pseudo code for Scheduler

**Comment by vadorvatsal** [comment]
I'll be concentrating on this issue

**Comment by vadorvatsal** [comment]
Important resources :

https://notes.shichao.io/lkd/ch14/

https://www.cs.princeton.edu/courses/archive/fall08/cos318/lectures/Lec11-Devices.pdf

https://researcher.watson.ibm.com/researcher/files/il-AVISHAY/01-block_io-v1.3.pdf

**Comment by rautranjan** [comment]
Commenting on behalf of @vatsalvador  

Following is the pseudo code for SBIOS: 

begin


initialize rb tree;
static void sbio.reqType(); // define the function for classifying requests by type
sbio.next();// define the function for scheduling next requests
sbio.disReq();// define the function for dispatching requests.
    do
   {
       if(new_request *req)
       {
         add_timestamp( *req);
         rb_tree.add(*req);
         then update rb_tree;
       }
      
      for(; while each node in tree is traversed;)
      {
       // update rb_tree;
      // For dispatching the requests
     if(timestamp *q > current.time)
     {
     sbio.next(*q)
     }
     else if(current.time>timestamp *q)
     {
          if(sbio.reqType == read)
          {
          // Check for write starvation
          then
          look for two different same size block
sbio.disReq(*q)
//dispatch read request to different block
          }

          else if(sbio.reqType == write)
          {
          //Keep the counter
          if( write counter is saturated )
          {
         //look for the priority and dispatch write request to same block
         
//It will starve write request but still internals parallelism for read request can be achieved without block crossing penalties 
          }
       
   }
          
     }

     }

   } while ();

end
