### ISSUE TITLE
Implementation of the SBIOS code

### ISSUE THREAD

**Issue by rautranjan** [rautranjan/os-ssd-scheduler#4]
Implementation of the SBIOS code as per psuedo code

**Comment by vadorvatsal** [comment]
source for elevator: https://elixir.bootlin.com/linux/v3.3/ident/elv_register

https://github.com/torvalds/linux

**Comment by vadorvatsal** [comment]
how module starts in linux kernel : https://www.kernel.org/doc/htmldocs/kernel-hacking/routines-init-again.html

**Comment by rautranjan** [comment]
Done with implementation
