### ISSUE TITLE
Performance analysis

### ISSUE THREAD

**Issue by rautranjan** [rautranjan/os-ssd-scheduler#6]
Find appropriate Benchmarks and test performance of SBIOS, noop, dynamic and cfq schedulers on SSD or SSD Simulator

**Comment by vadorvatsal** [comment]
https://github.com/Algodev-github/S

https://www.youtube.com/watch?v=1cjZeaCXIyM

**Comment by vadorvatsal** [comment]
Things to install before running benchmark tests

fio
iostat
awk
time
bc
pv
git
make
gnuplot
mplayer

mail transfer agent msmtp
mail client mailx

**Comment by rautranjan** [comment]
We used benchmarks using application ([link](https://github.com/Algodev-github/S)).

1. gnome terminal startup throughput
2. gnome terminal startup time
3. lowriter startup throughput
4. lowriter startup time
5. throughput for sequential and random read writes
6. video playing drop rate
7. video playing throughput
8. xterm startup throughput
9. xterm startup time
